// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TBS.PrintTest.DataAccess.Models
{
    public partial class EmployeeTermType
    {
        public EmployeeTermType()
        {
            Employee = new HashSet<Employee>();
        }

        public int EmployeeTermTypeId { get; set; }
        public string EmployeeTermTypeCode { get; set; }
        public string EmployeeTermTypeEnglishName { get; set; }
        public string EmployeeTermTypeFrenchName { get; set; }
        public int EmployeeTermTypeSortOrder { get; set; }
        public bool? EmployeeTermTypeActiveBoolean { get; set; }

        public virtual ICollection<Employee> Employee { get; set; }
    }
}