// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TBS.PrintTest.DataAccess.Models
{
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public int EmployeeTermTypeId { get; set; }
        public DateTime EmployeeStartDate { get; set; }
        public string EmployeeJobDescription { get; set; }
        public int EmployeeProvinceId { get; set; }
        public bool? EmployeeActiveBoolean { get; set; }

        public virtual Province EmployeeProvince { get; set; }
        public virtual EmployeeTermType EmployeeTermType { get; set; }
    }
}