//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBS.PrintTest.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBS.PrintTest.Web.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application title.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add employee.
        /// </summary>
        public static string ButtonAddEmployee {
            get {
                return ResourceManager.GetString("ButtonAddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to employee list.
        /// </summary>
        public static string ButtonBackToEmployeeList {
            get {
                return ResourceManager.GetString("ButtonBackToEmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes you back to the employee list.
        /// </summary>
        public static string ButtonBackToEmployeeListToolTip {
            get {
                return ResourceManager.GetString("ButtonBackToEmployeeListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete employee.
        /// </summary>
        public static string ButtonDeleteEmployeeToolTip {
            get {
                return ResourceManager.GetString("ButtonDeleteEmployeeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee.
        /// </summary>
        public static string ButtonEditEmployeeToolTip {
            get {
                return ResourceManager.GetString("ButtonEditEmployeeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ButtonView {
            get {
                return ResourceManager.GetString("ButtonView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View employee.
        /// </summary>
        public static string ButtonViewEmployeeToolTip {
            get {
                return ResourceManager.GetString("ButtonViewEmployeeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a province....
        /// </summary>
        public static string Codelookup_SelectProvince {
            get {
                return ResourceManager.GetString("Codelookup_SelectProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your questions and comments are important to us. If you need to contact us, you can reach us by:.
        /// </summary>
        public static string Contacts_Para1 {
            get {
                return ResourceManager.GetString("Contacts_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General and technical enquiries.
        /// </summary>
        public static string Contacts_SubTitle {
            get {
                return ResourceManager.GetString("Contacts_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts_Title {
            get {
                return ResourceManager.GetString("Contacts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display print view.
        /// </summary>
        public static string DisplayPrintView {
            get {
                return ResourceManager.GetString("DisplayPrintView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the add page to add a new employee record..
        /// </summary>
        public static string EmployeeAddPageDescription {
            get {
                return ResourceManager.GetString("EmployeeAddPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee has been added successfully..
        /// </summary>
        public static string EmployeeAddSuccessMessage {
            get {
                return ResourceManager.GetString("EmployeeAddSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add employee.
        /// </summary>
        public static string EmployeeAddTitle {
            get {
                return ResourceManager.GetString("EmployeeAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the edit page for an employee record..
        /// </summary>
        public static string EmployeeEditPageDescription {
            get {
                return ResourceManager.GetString("EmployeeEditPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee has been updated successfully..
        /// </summary>
        public static string EmployeeEditSuccessMessage {
            get {
                return ResourceManager.GetString("EmployeeEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee.
        /// </summary>
        public static string EmployeeEditTitle {
            get {
                return ResourceManager.GetString("EmployeeEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string EmployeeFirstName {
            get {
                return ResourceManager.GetString("EmployeeFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job description.
        /// </summary>
        public static string EmployeeJobDescription {
            get {
                return ResourceManager.GetString("EmployeeJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string EmployeeLastName {
            get {
                return ResourceManager.GetString("EmployeeLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string EmployeeListActions {
            get {
                return ResourceManager.GetString("EmployeeListActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example for viewing, adding and editing records in a table..
        /// </summary>
        public static string EmployeeListPageDescription {
            get {
                return ResourceManager.GetString("EmployeeListPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EmployeeListTitle {
            get {
                return ResourceManager.GetString("EmployeeListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string EmployeeProvince {
            get {
                return ResourceManager.GetString("EmployeeProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string EmployeeStartDate {
            get {
                return ResourceManager.GetString("EmployeeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employement term.
        /// </summary>
        public static string EmployeeTermType {
            get {
                return ResourceManager.GetString("EmployeeTermType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the readonly view of the employee record..
        /// </summary>
        public static string EmployeeViewPageDescription {
            get {
                return ResourceManager.GetString("EmployeeViewPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View employee.
        /// </summary>
        public static string EmployeeViewTitle {
            get {
                return ResourceManager.GetString("EmployeeViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred processing your request.  Please contact your system administrator..
        /// </summary>
        public static string GenericUntrappedErrorMessage {
            get {
                return ResourceManager.GetString("GenericUntrappedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GenericUntrappedErrorTitle {
            get {
                return ResourceManager.GetString("GenericUntrappedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Index_PageTitle {
            get {
                return ResourceManager.GetString("Home_Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the home page for your application..
        /// </summary>
        public static string Home_PageDescription {
            get {
                return ResourceManager.GetString("Home_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where we can explain what this template has to offer.  At the moment, we have a CRUD example for viewing, adding, editing and deleting employee records..
        /// </summary>
        public static string Home_Para1 {
            get {
                return ResourceManager.GetString("Home_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More example features will be added over time..
        /// </summary>
        public static string Home_Para2 {
            get {
                return ResourceManager.GetString("Home_Para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template introduction.
        /// </summary>
        public static string Home_SubTitle {
            get {
                return ResourceManager.GetString("Home_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be deleted.
        /// </summary>
        public static string ValidationSummary_Errors_Delete {
            get {
                return ResourceManager.GetString("ValidationSummary_Errors_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ValidationSummary_Errors_Header {
            get {
                return ResourceManager.GetString("ValidationSummary_Errors_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form could not be loaded.
        /// </summary>
        public static string ValidationSummary_Errors_List {
            get {
                return ResourceManager.GetString("ValidationSummary_Errors_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form could not be loaded.
        /// </summary>
        public static string ValidationSummary_Errors_Load {
            get {
                return ResourceManager.GetString("ValidationSummary_Errors_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be saved.
        /// </summary>
        public static string ValidationSummary_Errors_Save {
            get {
                return ResourceManager.GetString("ValidationSummary_Errors_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form could not be submitted.
        /// </summary>
        public static string ValidationSummary_Errors_Submit {
            get {
                return ResourceManager.GetString("ValidationSummary_Errors_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to because {0} errors were found..
        /// </summary>
        public static string ValidationSummary_ErrorsFound {
            get {
                return ResourceManager.GetString("ValidationSummary_ErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to because {0} error was found..
        /// </summary>
        public static string ValidationSummary_ErrorsFound_One {
            get {
                return ResourceManager.GetString("ValidationSummary_ErrorsFound_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ValidationSummary_Infos_Header {
            get {
                return ResourceManager.GetString("ValidationSummary_Infos_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} messages were found..
        /// </summary>
        public static string ValidationSummary_InfosFound {
            get {
                return ResourceManager.GetString("ValidationSummary_InfosFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message was found..
        /// </summary>
        public static string ValidationSummary_InfosFound_One {
            get {
                return ResourceManager.GetString("ValidationSummary_InfosFound_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ValidationSummary_Success {
            get {
                return ResourceManager.GetString("ValidationSummary_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ValidationSummary_Warnings_Header {
            get {
                return ResourceManager.GetString("ValidationSummary_Warnings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} warnings were found..
        /// </summary>
        public static string ValidationSummary_WarningsFound {
            get {
                return ResourceManager.GetString("ValidationSummary_WarningsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} warning was found..
        /// </summary>
        public static string ValidationSummary_WarningsFound_One {
            get {
                return ResourceManager.GetString("ValidationSummary_WarningsFound_One", resourceCulture);
            }
        }
    }
}
